const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
let settings={tension:'LOW',prepress:1};
let state=JSON.parse(localStorage.getItem('compactorSimStateV4')||'{"score":0,"streak":0,"coils":0,"faults":0,"health":{"head":100,"guide":100,"encoder":100,"io":100}}');
if(!state.health)state.health={head:100,guide:100,encoder:100,io:100};
let busy=false,soundOn=true,currentFault=null,selectedInspection=null,currentRole='operator',alarmAck=false,mechanicCalled=false;
const sensors=['B24','B28','B56','B58','B64','B69'];
const cycleNames=['Исходное','Подпрессовка','Подача','Натяжение','Низкая скорость','Скрутка','Резка','Возврат'];
const faults=[
{id:'b28',code:'ALM 128',sym:'Проволока подана, но импульсы движения пропали. Натяжение не подтверждается.',node:'B28 / кодировщик',alarm:'WIRE MOTION',inspect:'b28',repair:'Проверить B28, кодировщик и муфту',health:'encoder',hmi:{B28:'bad'},severity:'bad'},
{id:'plate2module',code:'ALM 226',sym:'После обвязки проволока остаётся свободной. Следующая подача может затолкнуть проволоку в направляющую пресс-плиты 2.',node:'Пресс-плита 2 / Node 26',alarm:'PRESS PLATE 2',inspect:'plate2',repair:'Проверить Node 26 / ET200S и сигналы B56 B58 B64 B69',health:'io',hmi:{B69:'bad'},severity:'bad'},
{id:'jam',code:'ALM 214',sym:'Проволока не проходит по направляющей пресс-плиты 2 и образует петлю.',node:'Направляющая PP2',alarm:'WIRE JAM PP2',inspect:'guide',repair:'Освободить направляющую и удалить зажатую проволоку',health:'guide',hmi:{B64:'bad'},severity:'bad'},
{id:'clamp',code:'ALM 305',sym:'Голова выполняет цикл, но скрутка распускается после резки.',node:'Неподвижный прижим вязальной головы',alarm:'HEAD CLAMP',inspect:'head',repair:'Проверить и заменить неподвижный прижим вязальной головы',health:'head',hmi:{},severity:'bad'},
{id:'head3',code:'ALM 303',sym:'Третья вязальная голова не завершила узел. Скрутка отсутствует.',node:'Вязальная голова 3',alarm:'HEAD 3 FAIL',inspect:'head',repair:'Проверить B1/B2/B3/B5/B8/B20, нож, прижим и механизм скрутки',health:'head',hmi:{},severity:'bad'},
{id:'weak',code:'WARN 610',sym:'Все головы завершили цикл, но обвязка получилась слабой.',node:'Контур натяжения',alarm:'LOW TENSION',inspect:'tension',repair:'Проверить ролики, импульсы к низкой скорости и фактическую утяжку',health:null,hmi:{},severity:'warn'}];
function save(){localStorage.setItem('compactorSimStateV4',JSON.stringify(state))}
function renderStats(){['score','streak','coils','faults'].forEach(k=>$(k).textContent=state[k]);$('headHealth').textContent=state.health.head+'%';$('guideHealth').textContent=state.health.guide+'%';$('encoderHealth').textContent=state.health.encoder+'%';$('ioHealth').textContent=state.health.io+'%'}
function log(t,type='info'){let e=document.createElement('div');e.className='log-entry '+type;e.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' · '+t;$('log').prepend(e)}
function badge(t,type=''){$('qualityBadge').textContent=t;$('qualityBadge').className='badge '+type}
function mstate(t,type='ok'){$('machineState').textContent=t;$('machineState').className=type==='ok'?'state-ok':type==='warn'?'state-warn':'state-bad';$('hmiState').textContent=t}
function beep(f=500,d=70){if(!soundOn)return;let A=window.AudioContext||window.webkitAudioContext;if(!A)return;let c=new A(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;o.connect(g);g.connect(c.destination);g.gain.value=.025;o.start();o.stop(c.currentTime+d/1000)}
function sensor(id,mode=false){let e=document.querySelector(`[data-sensor="${id}"] i`);if(e)e.className=mode===true?'on':mode==='bad'?'bad':'';let io=document.querySelector(`[data-io="${id}"] i`);if(io)io.className=e?e.className:''}
function buildSensors(){let a=$('sensorStrip'),b=$('ioPanel');sensors.forEach(s=>{a.insertAdjacentHTML('beforeend',`<div class="sensor" data-sensor="${s}"><span>${s}</span><i></i></div>`);b.insertAdjacentHTML('beforeend',`<div class="io-bit" data-io="${s}"><span>${s}</span><i></i></div>`)});[1,2,3,4].forEach(n=>$('headStatus').insertAdjacentHTML('beforeend',`<div class="io-bit"><span>HEAD ${n}</span><i id="hhead${n}"></i></div>`))}
function buildCycle(){cycleNames.forEach((n,i)=>$('cycleSteps').insertAdjacentHTML('beforeend',`<div class="step" data-step="${i}">${i+1}. ${n}</div>`))}
function step(i,status='active'){document.querySelectorAll('.step').forEach((e,j)=>{if(j<i)e.className='step done';else if(j===i)e.className='step '+status;else e.className='step'})}
function resetVisual(){document.querySelectorAll('.head').forEach(h=>h.className='head');document.querySelectorAll('.tie').forEach(s=>s.classList.remove('on','weak','bad'));$('jamWire').classList.remove('on');$('wireFeed').classList.remove('feeding');$('wireLoop').classList.remove('on','tight');$('pressRight').classList.remove('fault','in');$('pressLeft').classList.remove('in');$('coil').classList.remove('compressed');$('gapValue').textContent='100%';sensors.forEach(s=>sensor(s,false));for(let n=1;n<=4;n++)$('hhead'+n).className='';document.querySelectorAll('.step').forEach(e=>e.className='step')}
function switchTab(which){['operator','mechanic','hmi'].forEach(x=>{$(x+'View').classList.toggle('hidden',x!==which);$(x+'Tab').classList.toggle('active',x===which)})}
function setRole(role){currentRole=role;$('roleBadge').textContent=role==='operator'?'ОПЕРАТОР':'МЕХАНИК';$('roleGate').classList.add('hidden');switchTab(role);log(role==='operator'?'Смена принята оператором.':'Механик принял машину в работу.','info')}
$('chooseOperator').onclick=()=>setRole('operator');$('chooseMechanic').onclick=()=>setRole('mechanic');$('changeRoleBtn').onclick=()=>$('roleGate').classList.remove('hidden');
$('operatorTab').onclick=()=>switchTab('operator');$('mechanicTab').onclick=()=>switchTab('mechanic');$('hmiTab').onclick=()=>switchTab('hmi');$('returnBtn').onclick=()=>{setRole('operator')};$('callMechanicBtn').onclick=()=>{if(!currentFault){log('Активной аварии нет — вызов механика не требуется.','info');return}mechanicCalled=true;log('Оператор вызвал механика. Машина передана на диагностику.','warn');setRole('mechanic')};$('hmiOperator').onclick=()=>setRole('operator');$('hmiMechanic').onclick=()=>setRole('mechanic');
function setPair(a,b,on){$(a).classList.toggle('active',on);$(b).classList.toggle('active',!on)}
$('lowBtn').onclick=()=>{if(busy)return;settings.tension='LOW';setPair('lowBtn','highBtn',true);$('hmiTension').textContent='LOW';log('Оператор выбрал LOW.','info')};$('highBtn').onclick=()=>{if(busy)return;settings.tension='HIGH';setPair('highBtn','lowBtn',true);$('hmiTension').textContent='HIGH';log('Оператор выбрал HIGH.','info')};$('singleBtn').onclick=()=>{if(busy)return;settings.prepress=1;setPair('singleBtn','doubleBtn',true);$('hmiPrepress').textContent='1×'};$('doubleBtn').onclick=()=>{if(busy)return;settings.prepress=2;setPair('doubleBtn','singleBtn',true);$('hmiPrepress').textContent='2×'};$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊':'🔇'};
function degrade(){state.health.head=Math.max(45,state.health.head-(Math.random()<.45?1:0));state.health.guide=Math.max(45,state.health.guide-(Math.random()<.35?1:0));state.health.encoder=Math.max(45,state.health.encoder-(Math.random()<.25?1:0));state.health.io=Math.max(45,state.health.io-(Math.random()<.18?1:0))}
function chooseFault(){let avg=(state.health.head+state.health.guide+state.health.encoder+state.health.io)/4;let p=.14+(100-avg)/160;if(settings.tension==='HIGH')p+=.10;if(settings.prepress===2)p-=.025;if(Math.random()>p)return null;let weighted=faults.flatMap(f=>{let w=1;if(f.health)w+=Math.floor((100-state.health[f.health])/12);return Array(w).fill(f)});return weighted[Math.floor(Math.random()*weighted.length)]}
async function press(){step(1);mstate('ПОДПРЕССОВКА','warn');$('operatorTask').textContent='КОНТРОЛЬ ПРЕССА';log('Плиты сходятся слева и справа. Бунт укорачивается по оси и уплотняется.','info');$('pressLeft').classList.add('in');$('pressRight').classList.add('in');$('coil').classList.add('compressed');$('gapValue').textContent='76%';sensor('B58',true);beep(240,120);await wait(820);if(settings.prepress===2){$('gapValue').textContent='88%';$('pressLeft').classList.remove('in');$('pressRight').classList.remove('in');$('coil').classList.remove('compressed');await wait(420);$('pressLeft').classList.add('in');$('pressRight').classList.add('in');$('coil').classList.add('compressed');$('gapValue').textContent='72%';log('Выполнена вторая подпрессовка.','info');await wait(760)}}
async function runCycle(){if(busy||currentRole!=='operator')return;if(currentFault){log('Нельзя запускать новый цикл: активная неисправность не устранена.','bad');return}busy=true;$('startBtn').disabled=true;alarmAck=false;mechanicCalled=false;resetVisual();$('faultCode').textContent='НЕТ АВАРИИ';$('faultCode').className='badge';$('mechanicPrompt').textContent='Ожидание вызова оператора.';$('hmiAlarm').textContent='—';badge('ЦИКЛ');$('operatorTask').textContent='ЦИКЛ ЗАПУЩЕН';log(`Старт цикла: ${settings.tension}, подпрессовка ${settings.prepress}×.`);step(0);sensor('B56',true);sensor('B64',true);await wait(350);await press();step(2);mstate('ПОДАЧА ПРОВОЛОКИ','warn');$('operatorTask').textContent='ПОДАЧА';$('wireFeed').classList.add('feeding');$('wireLoop').classList.add('on');sensor('B24',true);log('Головы подают проволоку через направляющие вокруг сжатого бунта.','info');await wait(850);sensor('B28',true);sensor('B69',true);$('wireFeed').classList.remove('feeding');step(3);mstate('НАТЯЖЕНИЕ','warn');$('wireLoop').classList.add('tight');$('operatorTask').textContent='НАТЯЖЕНИЕ';log('Трайбаппарат выбирает слабину и утягивает петлю.','info');await wait(700);step(4);mstate('НИЗКАЯ СКОРОСТЬ','warn');await wait(400);currentFault=chooseFault();if(currentFault?.id==='b28')sensor('B28','bad');if(currentFault?.id==='plate2module'){sensor('B69','bad');$('pressRight').classList.add('fault')}if(currentFault?.id==='jam'){$('jamWire').classList.add('on');sensor('B64','bad');$('pressRight').classList.add('fault')}
step(5);mstate('СКРУТКА','warn');$('operatorTask').textContent='СКРУТКА';log('Вязальные головы формируют узлы.','info');for(let i=1;i<=4;i++){let h=document.querySelector(`[data-head="${i}"]`);await wait(420);let fail=(currentFault?.id==='head3'&&i===3)||(currentFault?.id==='clamp'&&i===2);if(fail){h.classList.add('fail');$('hhead'+i).className='bad';$(`strap${i}`).classList.add('on','bad');beep(130,150)}else{h.classList.add('ok');$('hhead'+i).className='on';$(`strap${i}`).classList.add('on');if(currentFault?.id==='weak')$(`strap${i}`).classList.add('weak');beep(510+i*30,60)}}step(6);mstate('РЕЗКА','warn');$('operatorTask').textContent='РЕЗКА';await wait(500);$('wireLoop').classList.remove('on','tight');step(7);mstate('ВОЗВРАТ','warn');$('pressLeft').classList.remove('in');$('pressRight').classList.remove('in');$('coil').classList.remove('compressed');$('gapValue').textContent='100%';await wait(560);degrade();
if(currentFault){state.faults++;state.streak=0;state.score=Math.max(0,state.score-20);$('faultCode').textContent=currentFault.code;$('faultCode').className='badge '+currentFault.severity;$('mechanicPrompt').textContent='Вызов от оператора. Симптом: '+currentFault.sym;$('hmiAlarm').textContent=currentFault.alarm;Object.entries(currentFault.hmi).forEach(([k,v])=>sensor(k,v));badge(currentFault.severity==='warn'?'ПРЕДУПР.':'АВАРИЯ',currentFault.severity);mstate(currentFault.severity==='warn'?'ПРЕДУПРЕЖДЕНИЕ':'АВАРИЯ',currentFault.severity);$('operatorTask').textContent='ОСТАНОВ / ВЫЗОВ МЕХАНИКА';log(currentFault.code+': '+currentFault.sym,currentFault.severity);step(7,'fail');buildInspection()}else{state.coils++;state.streak++;state.score+=100+Math.min(state.streak*5,50);badge(settings.tension==='LOW'?'КАЧЕСТВО 100%':'КАЧЕСТВО 84%',settings.tension==='LOW'?'good':'warn');mstate('ГОТОВО','ok');$('operatorTask').textContent='БУНТ ГОТОВ';log('Цикл завершён. Четыре обвязки сформированы.','good');step(7,'done')}renderStats();save();busy=false;$('startBtn').disabled=false}
function buildInspection(){let g=$('inspectionGrid');g.innerHTML='';[['b28','B28 / кодировщик'],['plate2','Пресс-плита 2 / Node 26'],['guide','Направляющая PP2'],['head','Вязальная голова'],['tension','Контур натяжения']].forEach(([id,label])=>{let b=document.createElement('button');b.textContent='Проверить: '+label;b.onclick=()=>inspect(id,b);g.appendChild(b)});$('repairPanel').classList.add('hidden')}
function inspect(id,b){if(!currentFault){log('Механик: активной аварии нет. Можно выполнить профилактику.','info');return}selectedInspection=id;document.querySelectorAll('#inspectionGrid button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');if(id===currentFault.inspect){state.score+=15;log('Механик обнаружил признак неисправности в узле: '+currentFault.node+'.','good');showRepairs()}else{state.score=Math.max(0,state.score-5);log('Проверенный узел выглядит исправным.','warn')}renderStats();save()}
function showRepairs(){let p=$('repairPanel'),a=$('repairActions');p.classList.remove('hidden');a.innerHTML='';let choices=[currentFault.repair,'Сбросить аварию без проверки','Увеличить скорость цикла','Заменить случайный датчик'].sort(()=>Math.random()-.5);choices.forEach(t=>{let b=document.createElement('button');b.textContent=t;b.onclick=()=>repair(t,b);a.appendChild(b)})}
function repair(t,b){if(t===currentFault.repair){b.classList.add('good-choice');state.score+=60;if(currentFault.health)state.health[currentFault.health]=100;log('Механик устранил причину: '+currentFault.node+'.','good');badge('УСТРАНЕНО','good');$('hmiAlarm').textContent='—';mstate('ГОТОВ','ok');$('operatorTask').textContent='ГОТОВ К ЦИКЛУ';currentFault=null;$('faultCode').textContent='УСТРАНЕНО';$('faultCode').className='badge good';$('mechanicPrompt').textContent='Ремонт завершён. Передай машину оператору.';$('repairPanel').classList.add('hidden');resetVisual()}else{b.classList.add('bad-choice');state.score=Math.max(0,state.score-15);log('Действие не устранило неисправность.','bad')}renderStats();save()}
function ackAlarm(){if(!currentFault){log('Нет активной аварии для квитирования.','info');return}alarmAck=true;log('Оператор квитировал сообщение HMI. Причина аварии не устранена.','warn');$('operatorTask').textContent='ВЫЗОВИ МЕХАНИКА'}
$('ackBtn').onclick=ackAlarm;$('hmiAck').onclick=ackAlarm;
document.querySelectorAll('[data-maint]').forEach(b=>b.onclick=()=>{let type=b.dataset.maint;if(type==='clean'){state.health.head=100;log('Механик очистил и продул вязальные головы.','good')}if(type==='guide'){state.health.guide=100;log('Направляющая пресс-плиты 2 очищена.','good')}if(type==='encoder'){state.health.encoder=100;log('Проверены B28, кодировщик и муфта.','good')}if(type==='io'){state.health.io=100;log('Проверены разъёмы и модули Node 26.','good')}state.score+=5;renderStats();save()});
$('startBtn').onclick=runCycle;$('resetBtn').onclick=()=>{if(busy)return;state={score:0,streak:0,coils:0,faults:0,health:{head:100,guide:100,encoder:100,io:100}};currentFault=null;save();renderStats();resetVisual();badge('—');mstate('ГОТОВ','ok');$('hmiAlarm').textContent='—';$('operatorTask').textContent='ГОТОВ К ЦИКЛУ';$('mechanicPrompt').textContent='Прогресс сброшен.';log('Полный сброс тренажёра.')};
buildSensors();buildCycle();buildInspection();renderStats();