const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
let settings={tension:'LOW',prepress:1};
let state=JSON.parse(localStorage.getItem('compactorSimStateV2')||'{"score":0,"streak":0,"coils":0,"faults":0}');
let busy=false,soundOn=true,currentFault=null,selectedInspection=null;
const sensors=['B24','B28','B56','B58','B64','B69'];
const cycleNames=['Исходное','Подпрессовка','Подача','Натяжение','Низкая скорость','Скрутка','Резка','Возврат'];
const faults=[
{id:'b28',code:'ALM 128',sym:'Проволока подана, но импульсы движения пропали. Натяжение не подтверждается.',node:'B28 / кодировщик',alarm:'WIRE MOTION',inspect:'b28',repair:'Проверить B28, кодировщик и муфту',hmi:{B28:'bad'},severity:'bad'},
{id:'plate2module',code:'ALM 226',sym:'После обвязки проволока остаётся свободной. На следующем цикле появляется риск заталкивания проволоки в направляющую пресс-плиты 2.',node:'Пресс-плита 2 / I/O',alarm:'PRESS PLATE 2',inspect:'plate2',repair:'Проверить Node 26 / ET200S и сигналы B56 B58 B64 B69',hmi:{B69:'bad'},severity:'bad'},
{id:'jam',code:'ALM 214',sym:'Проволока не проходит по направляющей пресс-плиты 2 и образует петлю.',node:'Направляющая PP2',alarm:'WIRE JAM PP2',inspect:'guide',repair:'Освободить направляющую и удалить зажатую проволоку',hmi:{B64:'bad'},severity:'bad'},
{id:'clamp',code:'ALM 305',sym:'Одна вязальная голова выполняет цикл, но скрутка распускается после резки.',node:'Неподвижный прижим',alarm:'HEAD CLAMP',inspect:'head',repair:'Проверить/заменить неподвижный прижим вязальной головы',hmi:{},severity:'bad'},
{id:'head3',code:'ALM 303',sym:'Третья вязальная голова не завершила узел. Скрутка отсутствует.',node:'Вязальная голова 3',alarm:'HEAD 3 FAIL',inspect:'head',repair:'Проверить B1/B2/B3/B5/B8/B20, нож, прижим и механизм скрутки',hmi:{},severity:'bad'},
{id:'weak',code:'WARN 610',sym:'Все головы завершили цикл, но обвязка получилась слабой.',node:'Контур натяжения',alarm:'LOW TENSION',inspect:'tension',repair:'Проверить ролики, переход к низкой скорости и фактическую утяжку',hmi:{},severity:'warn'}];
function save(){localStorage.setItem('compactorSimStateV2',JSON.stringify(state))}
function renderStats(){['score','streak','coils','faults'].forEach(k=>$(k).textContent=state[k])}
function log(t,type='info'){let e=document.createElement('div');e.className='log-entry '+type;e.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' · '+t;$('log').prepend(e)}
function badge(t,type=''){$('qualityBadge').textContent=t;$('qualityBadge').className='badge '+type}
function mstate(t,type='ok'){$('machineState').textContent=t;$('machineState').className=type==='ok'?'state-ok':type==='warn'?'state-warn':'state-bad';$('hmiState').textContent=t}
function beep(f=500,d=70){if(!soundOn)return;let A=window.AudioContext||window.webkitAudioContext;if(!A)return;let c=new A(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;o.connect(g);g.connect(c.destination);g.gain.value=.03;o.start();o.stop(c.currentTime+d/1000)}
function sensor(id,mode=false){let e=document.querySelector(`[data-sensor="${id}"] i`);if(e)e.className=mode===true?'on':mode==='bad'?'bad':'';let io=document.querySelector(`[data-io="${id}"] i`);if(io)io.className=e?e.className:''}
function buildSensors(){let a=$('sensorStrip'),b=$('ioPanel');sensors.forEach(s=>{a.insertAdjacentHTML('beforeend',`<div class="sensor" data-sensor="${s}"><span>${s}</span><i></i></div>`);b.insertAdjacentHTML('beforeend',`<div class="io-bit" data-io="${s}"><span>${s}</span><i></i></div>`)});let hs=$('headStatus');[1,2,3,4].forEach(n=>hs.insertAdjacentHTML('beforeend',`<div class="io-bit"><span>HEAD ${n}</span><i id="hhead${n}"></i></div>`))}
function buildCycle(){cycleNames.forEach((n,i)=>$('cycleSteps').insertAdjacentHTML('beforeend',`<div class="step" data-step="${i}">${i+1}. ${n}</div>`))}
function step(i,status='active'){document.querySelectorAll('.step').forEach((e,j)=>{if(j<i)e.className='step done';else if(j===i)e.className='step '+status;else e.className='step'})}
function resetVisual(){document.querySelectorAll('.head').forEach(h=>h.className='head');document.querySelectorAll('.tie').forEach(s=>s.classList.remove('on','weak','bad'));$('jamWire').classList.remove('on');$('pressRight').classList.remove('fault');$('pressLeft').classList.remove('in');$('pressRight').classList.remove('in');$('coil').classList.remove('compressed');$('gapValue').textContent='100%';sensors.forEach(s=>sensor(s,false));for(let n=1;n<=4;n++)$('hhead'+n).className='';document.querySelectorAll('.step').forEach(e=>e.className='step')}
function switchTab(which){['operator','mechanic','hmi'].forEach(x=>{$(x+'View').classList.toggle('hidden',x!==which);$(x+'Tab').classList.toggle('active',x===which)})}
['operator','mechanic','hmi'].forEach(x=>$(x+'Tab').onclick=()=>switchTab(x));$('toMechanicBtn').onclick=()=>switchTab('mechanic');$('returnBtn').onclick=()=>switchTab('operator');
function setPair(a,b,on){$(a).classList.toggle('active',on);$(b).classList.toggle('active',!on)}
$('lowBtn').onclick=()=>{if(busy)return;settings.tension='LOW';setPair('lowBtn','highBtn',true);$('hmiTension').textContent='LOW'};$('highBtn').onclick=()=>{if(busy)return;settings.tension='HIGH';setPair('highBtn','lowBtn',true);$('hmiTension').textContent='HIGH'};$('singleBtn').onclick=()=>{if(busy)return;settings.prepress=1;setPair('singleBtn','doubleBtn',true);$('hmiPrepress').textContent='1×'};$('doubleBtn').onclick=()=>{if(busy)return;settings.prepress=2;setPair('doubleBtn','singleBtn',true);$('hmiPrepress').textContent='2×'};$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊':'🔇'};
function chooseFault(){let p=.24;if(settings.tension==='HIGH')p+=.12;if(settings.prepress===2)p-=.03;if(Math.random()>p)return null;return faults[Math.floor(Math.random()*faults.length)]}
async function press(){step(1);mstate('ПОДПРЕССОВКА','warn');log('Пресс-плиты сходятся. Бунт сжимается по оси между плитами.','info');$('pressLeft').classList.add('in');$('pressRight').classList.add('in');$('coil').classList.add('compressed');$('gapValue').textContent='76%';sensor('B58',true);beep(250,100);await wait(700);if(settings.prepress===2){log('Первая подпрессовка завершена. Короткий отпуск и повторное сжатие.','info');$('pressLeft').classList.remove('in');$('pressRight').classList.remove('in');$('coil').classList.remove('compressed');$('gapValue').textContent='88%';await wait(380);$('pressLeft').classList.add('in');$('pressRight').classList.add('in');$('coil').classList.add('compressed');$('gapValue').textContent='72%';beep(285,100);await wait(650)}}
async function runCycle(){if(busy)return;busy=true;$('startBtn').disabled=true;currentFault=null;selectedInspection=null;resetVisual();$('faultCode').textContent='НЕТ АВАРИИ';$('mechanicPrompt').textContent='Цикл выполняется…';$('hmiAlarm').textContent='—';badge('ЦИКЛ');log(`Старт: ${settings.tension}, подпрессовка ${settings.prepress}×.`);step(0);sensor('B56',true);sensor('B64',true);await wait(350);await press();step(2);mstate('ПОДАЧА ПРОВОЛОКИ','warn');log('Проволока проходит по направляющим вокруг сжатого бунта.','info');sensor('B24',true);await wait(450);sensor('B28',true);sensor('B69',true);await wait(420);step(3);mstate('НАТЯЖЕНИЕ','warn');log('Трайбаппарат выбирает слабину и натягивает проволоку на поверхности бунта.','info');await wait(420);step(4);mstate('НИЗКАЯ СКОРОСТЬ','warn');await wait(340);currentFault=chooseFault();if(currentFault?.id==='b28')sensor('B28','bad');if(currentFault?.id==='plate2module'){sensor('B69','bad');$('pressRight').classList.add('fault')}if(currentFault?.id==='jam'){$('jamWire').classList.add('on');sensor('B64','bad');$('pressRight').classList.add('fault')}
step(5);mstate('СКРУТКА','warn');log('Вязальные головы поочерёдно формируют и затягивают обвязки.','info');for(let i=1;i<=4;i++){let h=document.querySelector(`[data-head="${i}"]`);await wait(380);let fail=(currentFault?.id==='head3'&&i===3)||(currentFault?.id==='clamp'&&i===2);if(fail){h.classList.add('fail');$('hhead'+i).className='bad';$(`strap${i}`).classList.add('on','bad');beep(130,140)}else{h.classList.add('ok');$('hhead'+i).className='on';$(`strap${i}`).classList.add('on');if(currentFault?.id==='weak')$(`strap${i}`).classList.add('weak');beep(520+i*25,60)}}step(6);mstate('РЕЗКА','warn');log('Скрутка завершена, лишняя проволока отрезается.','info');await wait(420);step(7);mstate('ВОЗВРАТ','warn');$('pressLeft').classList.remove('in');$('pressRight').classList.remove('in');$('coil').classList.remove('compressed');$('gapValue').textContent='100%';await wait(500);
if(currentFault){state.faults++;state.streak=0;state.score=Math.max(0,state.score-20);$('faultCode').textContent=currentFault.code;$('faultCode').className='badge '+currentFault.severity;$('mechanicPrompt').textContent='Симптом: '+currentFault.sym;$('hmiAlarm').textContent=currentFault.alarm;Object.entries(currentFault.hmi).forEach(([k,v])=>sensor(k,v));badge(currentFault.severity==='warn'?'ПРЕДУПР.':'АВАРИЯ',currentFault.severity);mstate(currentFault.severity==='warn'?'ПРЕДУПРЕЖДЕНИЕ':'АВАРИЯ',currentFault.severity);log(currentFault.code+': '+currentFault.sym,currentFault.severity);step(7,'fail');buildInspection();}else{state.coils++;state.streak++;state.score+=100+Math.min(state.streak*5,50);$('mechanicPrompt').textContent='Неисправностей нет. Все узлы завершили цикл.';badge(settings.tension==='LOW'?'КАЧЕСТВО 100%':'КАЧЕСТВО 84%',settings.tension==='LOW'?'good':'warn');mstate('ГОТОВО','ok');log('Цикл завершён. Обвязки сформированы на сжатом бунте.','good');step(7,'done')}renderStats();save();busy=false;$('startBtn').disabled=false}
function buildInspection(){let g=$('inspectionGrid');g.innerHTML='';let opts=[['b28','B28 / кодировщик'],['plate2','Пресс-плита 2 / I/O'],['guide','Направляющая проволоки'],['head','Вязальная голова'],['tension','Контур натяжения']];opts.forEach(([id,label])=>{let b=document.createElement('button');b.textContent='Проверить: '+label;b.onclick=()=>inspect(id,b);g.appendChild(b)});$('repairPanel').classList.add('hidden')}
function inspect(id,b){if(!currentFault){log('Активной аварии нет.','info');return}selectedInspection=id;document.querySelectorAll('#inspectionGrid button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');if(id===currentFault.inspect){state.score+=15;log('Проверка дала полезный признак. Узел подозрительный.','good');showRepairs()}else{state.score=Math.max(0,state.score-5);log('Явной причины в этом узле не найдено.','warn')}renderStats();save()}
function showRepairs(){let p=$('repairPanel'),a=$('repairActions');p.classList.remove('hidden');a.innerHTML='';let choices=[currentFault.repair,'Сбросить аварию без проверки','Заменить все датчики','Увеличить скорость цикла'].sort(()=>Math.random()-.5);choices.forEach(t=>{let b=document.createElement('button');b.textContent=t;b.onclick=()=>repair(t,b);a.appendChild(b)})}
function repair(t,b){if(t===currentFault.repair){b.classList.add('good-choice');state.score+=60;log('Причина устранена: '+currentFault.node+'.','good');badge('УСТРАНЕНО','good');$('hmiAlarm').textContent='—';mstate('ГОТОВ','ok');currentFault=null;$('faultCode').textContent='УСТРАНЕНО';$('mechanicPrompt').textContent='Ремонт выполнен. Можно запускать следующий бунт.';$('repairPanel').classList.add('hidden');resetVisual()}else{b.classList.add('bad-choice');state.score=Math.max(0,state.score-15);log('Действие не устранило причину.','bad')}renderStats();save()}
$('startBtn').onclick=runCycle;$('resetBtn').onclick=()=>{if(busy)return;state={score:0,streak:0,coils:0,faults:0};save();renderStats();currentFault=null;resetVisual();badge('—');mstate('ГОТОВ','ok');$('hmiAlarm').textContent='—';$('mechanicPrompt').textContent='Прогресс сброшен. Запусти цикл.';log('Полный сброс тренажёра.')};
buildSensors();buildCycle();renderStats();buildInspection();