const $=id=>document.getElementById(id), wait=ms=>new Promise(r=>setTimeout(r,ms));
const heads=[1,2,3,4], sensors=['B24','B28','B56','B58','B64','B69'];
let settings={tension:'LOW',prepress:1};
let state=JSON.parse(localStorage.getItem('compactorSimStateV5')||'{"score":0,"streak":0,"coils":0,"faults":0,"health":{"head":100,"guide":100,"encoder":100,"io":100,"tension":100}}');
if(!state.health) state.health={head:100,guide:100,encoder:100,io:100,tension:100};
if(state.health.tension==null) state.health.tension=100;
let busy=false,soundOn=true,currentFault=null,currentRole='operator',alarmAck=false,mechanicCalled=false,currentPass=0,selectedFeedUnit=1,selectedHeadUnit=1,hmiPage='plc';
let enc=heads.map(()=>({pos:0,speed:0,moving:false}));
let headIO=heads.map(()=>({Y1:false,Y2:false,Y3:false,Y5:false,B1:true,B3:false,B5:false,B8:false,B20:true}));
let machineIO={B24:false,B28:false,B56:false,B58:false,B64:false,B69:false};

const cycleNames=['Исходное','Сжатие','Подача 1','Утяжка 1','Вязка 1: 4 головы','Подача 2','Утяжка 2','Вязка 2: 4 головы','Резка','Возврат'];
const faults=[
 {id:'b28',code:'ALM 128',sym:'Проволока подана, но импульсы движения пропали. Один из счётчиков U1–U4 перестал изменяться.',node:'B28 / кодировщик / муфта',alarm:'WIRE MOTION',inspect:'b28',repair:'Проверить B28, кодировщик и муфту; восстановить импульсы',health:'encoder',severity:'bad'},
 {id:'plate2module',code:'ALM 226',sym:'После вязки проволока остаётся свободной; следующая подача может уйти в направляющую пресс-плиты 2.',node:'Press plate 2 / Node 26',alarm:'PRESS PLATE 2',inspect:'plate2',repair:'Проверить Node 26 / ET200S и сигналы B56 B58 B64 B69',health:'io',severity:'bad'},
 {id:'jam',code:'ALM 214',sym:'Проволока образовала петлю в направляющей пресс-плиты 2 и не дошла до головы.',node:'Направляющая PP2',alarm:'WIRE JAM PP2',inspect:'guide',repair:'Освободить направляющую и удалить зажатую проволоку',health:'guide',severity:'bad'},
 {id:'clamp',code:'ALM 305',sym:'Одна голова завершила движение, но скрутка распускается после резки.',node:'Неподвижный прижим вязальной головы',alarm:'HEAD CLAMP',inspect:'head',repair:'Проверить/заменить неподвижный прижим и проверить удержание проволоки',health:'head',severity:'bad'},
 {id:'head3',code:'ALM 303',sym:'Голова 3 не формирует узел в одном из двух проходов.',node:'Вязальная голова 3',alarm:'HEAD 3 FAIL',inspect:'head',repair:'Проверить B1/B3/B5/B8/B20, Y1/Y2/Y3/Y5, нож и скрутчик',health:'head',severity:'bad'},
 {id:'weak',code:'WARN 610',sym:'Обе серии вязок выполнены, но утяжка слабая. Скорость/импульсы натяжения не соответствуют ожидаемым.',node:'Контур натяжения',alarm:'LOW TENSION',inspect:'tension',repair:'Проверить ролики, Y22A/Y22B, B24/B28 и переход на низкую скорость',health:'tension',severity:'warn'}
];

function save(){localStorage.setItem('compactorSimStateV5',JSON.stringify(state))}
function renderStats(){['score','streak','coils','faults'].forEach(k=>$(k).textContent=state[k]);$('headHealth').textContent=state.health.head+'%';$('guideHealth').textContent=state.health.guide+'%';$('encoderHealth').textContent=state.health.encoder+'%';$('ioHealth').textContent=state.health.io+'%';$('tensionHealth').textContent=state.health.tension+'%'}
function log(t,type='info'){let e=document.createElement('div');e.className='log-entry '+type;e.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' · '+t;$('log').prepend(e)}
function badge(t,type=''){$('qualityBadge').textContent=t;$('qualityBadge').className='badge '+type}
function mstate(t,type='ok'){$('machineState').textContent=t;$('machineState').className=type==='ok'?'state-ok':type==='warn'?'state-warn':'state-bad'}
function beep(f=500,d=70){if(!soundOn)return;let A=window.AudioContext||window.webkitAudioContext;if(!A)return;let c=new A(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;o.connect(g);g.connect(c.destination);g.gain.value=.022;o.start();o.stop(c.currentTime+d/1000)}
function lamp(el,on,bad=false){if(!el)return;el.className=(el.classList.contains('mini-lamp')?'mini-lamp':'lamp')+(bad?' bad':on?' on':'')}
function setMachineSensor(id,value,bad=false){machineIO[id]=value;let a=document.querySelector(`[data-sensor="${id}"] i`),b=document.querySelector(`[data-machineio="${id}"] i`);if(a)a.className=bad?'bad':value?'on':'';if(b)b.className=bad?'bad':value?'on':''}
function step(i,status='active'){document.querySelectorAll('.step').forEach((e,j)=>e.className='step '+(j<i?'done':j===i?status:''))}
function setPass(p){currentPass=p;$('passValue').textContent=p?`${p} / 2`:'—'}
function setPair(a,b,on){$(a).classList.toggle('active',on);$(b).classList.toggle('active',!on)}
function switchTab(which){['operator','mechanic','hmi'].forEach(x=>{$(x+'View').classList.toggle('hidden',x!==which);$(x+'Tab').classList.toggle('active',x===which)})}
function setRole(role){currentRole=role;$('roleBadge').textContent=role==='operator'?'ОПЕРАТОР':'МЕХАНИК';$('roleGate').classList.add('hidden');switchTab(role);log(role==='operator'?'Оператор принял машину.':'Механик принял машину.','info')}
function showHmi(page='plc'){switchTab('hmi');setHmiPage(page)}
function setHmiPage(page){hmiPage=page;document.querySelectorAll('.hmi-page-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('hmiPlcPage').classList.toggle('hidden',page!=='plc');$('hmiFeederPage').classList.toggle('hidden',page!=='feeder');$('hmiHeadPage').classList.toggle('hidden',page!=='head');renderHmi()}

function buildSensors(){let a=$('sensorStrip');sensors.forEach(s=>a.insertAdjacentHTML('beforeend',`<div class="sensor" data-sensor="${s}"><span>${s}</span><i></i></div>`));let m=$('machineIoPanel');sensors.forEach(s=>m.insertAdjacentHTML('beforeend',`<div class="io-bit" data-machineio="${s}"><span>${s}</span><i></i></div>`))}
function buildCycle(){cycleNames.forEach((n,i)=>$('cycleSteps').insertAdjacentHTML('beforeend',`<div class="step" data-step="${i}">${i+1}. ${n}</div>`))}
function plcRows(){return [['B24','Наличие проволоки'],['B28','Импульсы движения'],['B20','Голова в исходном'],['B5','Прижим/зажим'],['B1','Датчик головы 1'],['B3','Датчик головы 3']]}
function outRows(){return [['Y1','Зажим'],['Y2','Окручивание'],['Y3','Нож'],['Y5','Возврат']]}
function buildPlcTables(){
 let inp='<table class="plc-table"><tr><th>Вход</th>'+heads.map(n=>`<th>U${n}</th>`).join('')+'</tr>';
 plcRows().forEach(([id,name])=>{inp+=`<tr><td>${id} ${name}</td>`+heads.map(n=>`<td><i class="mini-lamp" data-plcin="${id}" data-unit="${n}"></i></td>`).join('')+'</tr>'});inp+='</table>';$('plcInputs').innerHTML=inp;
 let out='<table class="plc-table"><tr><th>Выход</th>'+heads.map(n=>`<th>U${n}</th>`).join('')+'</tr>';
 outRows().forEach(([id,name])=>{out+=`<tr><td>${id} ${name}</td>`+heads.map(n=>`<td><i class="mini-lamp" data-plcout="${id}" data-unit="${n}"></i></td>`).join('')+'</tr>'});out+='</table>';$('plcOutputs').innerHTML=out;
 $('encoderGrid').innerHTML=heads.map(n=>`<div class="encoder-unit"><b>U${n}</b><strong id="encPos${n}">0</strong><small>скорость <span id="encSpd${n}">0</span></small></div>`).join('');
}

function resetHeadIo(){headIO=heads.map(()=>({Y1:false,Y2:false,Y3:false,Y5:false,B1:true,B3:false,B5:false,B8:false,B20:true}))}
function resetVisual(){document.querySelectorAll('.head').forEach(h=>h.className='head');document.querySelectorAll('.tie').forEach(t=>t.classList.remove('on','weak','bad'));$('jamWire').classList.remove('on');$('wireFeed').classList.remove('feeding');$('wireLoop').classList.remove('on','tight');$('pressRight').classList.remove('fault','in');$('pressLeft').classList.remove('in');$('coil').classList.remove('compressed','finished');$('gapValue').textContent='100%';setPass(0);sensors.forEach(s=>setMachineSensor(s,false));enc=heads.map(()=>({pos:0,speed:0,moving:false}));resetHeadIo();document.querySelectorAll('.step').forEach(e=>e.className='step');renderHmi()}

function renderHmi(){
 $('hmiClock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
 heads.forEach((n,i)=>{if($('encPos'+n))$('encPos'+n).textContent=Math.round(enc[i].pos);if($('encSpd'+n))$('encSpd'+n).textContent=Math.round(enc[i].speed)});
 document.querySelectorAll('[data-plcin]').forEach(el=>{let i=+el.dataset.unit-1,id=el.dataset.plcin;let v=false,bad=false;if(id==='B24')v=machineIO.B24;if(id==='B28'){v=enc[i].moving;bad=currentFault?.id==='b28'&&i===2}if(id==='B20')v=headIO[i].B20;if(id==='B5')v=headIO[i].B5;if(id==='B1')v=headIO[i].B1;if(id==='B3')v=headIO[i].B3;el.className='mini-lamp'+(bad?' bad':v?' on':'')});
 document.querySelectorAll('[data-plcout]').forEach(el=>{let i=+el.dataset.unit-1,id=el.dataset.plcout,v=headIO[i][id];el.className='mini-lamp'+(v?' on':'')});
 let fi=selectedFeedUnit-1;$('feederUnitTitle').textContent=selectedFeedUnit;$('feedPosition').textContent=Math.round(enc[fi].pos);$('feedSpeed').textContent=Math.round(enc[fi].speed);lamp($('feedB24'),machineIO.B24);lamp($('feedB28'),enc[fi].moving,currentFault?.id==='b28'&&fi===2);lamp($('feedY22A'),headIO[fi].Y1);lamp($('feedY22B'),headIO[fi].Y2);
 let hi=selectedHeadUnit-1;$('headUnitTitle').textContent=selectedHeadUnit;['Y1','Y2','Y3','Y5'].forEach(k=>lamp($('h'+k.toLowerCase()),headIO[hi][k]));['B1','B3','B5','B8','B20'].forEach(k=>lamp($('h'+k.toLowerCase()),headIO[hi][k],currentFault?.id==='head3'&&hi===2&&k==='B3'));
}
function tickEnc(seconds=.6){return new Promise(resolve=>{let ticks=Math.max(3,Math.round(seconds*10)),c=0;let timer=setInterval(()=>{enc.forEach(e=>{if(e.moving){let delta=Math.max(8,e.speed/14)+(Math.random()*8-4);e.pos+=delta}});renderHmi();if(++c>=ticks){clearInterval(timer);resolve()}},100)})}
function setEncoderPhase(speed,moving=true){enc.forEach(e=>{e.speed=speed+Math.round(Math.random()*50-25);e.moving=moving});if(currentFault?.id==='b28'&&currentPass>0){enc[2].moving=false;enc[2].speed=0}renderHmi()}

function degrade(){let d=(k,p)=>{if(Math.random()<p)state.health[k]=Math.max(45,state.health[k]-1)};d('head',.5);d('guide',.35);d('encoder',.25);d('io',.2);d('tension',.35)}
function chooseFault(){let avg=Object.values(state.health).reduce((a,b)=>a+b,0)/5;let p=.12+(100-avg)/170;if(settings.tension==='HIGH')p+=.10;if(settings.prepress===2)p-=.02;if(Math.random()>p)return null;let weighted=faults.flatMap(f=>{let w=1;if(f.health)w+=Math.floor((100-state.health[f.health])/12);return Array(w).fill(f)});let f=weighted[Math.floor(Math.random()*weighted.length)];return {...f,pass:Math.random()<.55?1:2}}

async function press(){step(1);mstate('ПОДПРЕССОВКА','warn');$('operatorTask').textContent='КОНТРОЛЬ ПРЕССА';log('Пресс-плиты сходятся слева и справа. Бунт укорачивается по оси.','info');setMachineSensor('B56',true);setMachineSensor('B64',true);$('pressLeft').classList.add('in');$('pressRight').classList.add('in');$('coil').classList.add('compressed');$('gapValue').textContent='76%';setMachineSensor('B58',true);beep(240,120);await wait(1000);if(settings.prepress===2){$('gapValue').textContent='88%';$('pressLeft').classList.remove('in');$('pressRight').classList.remove('in');$('coil').classList.remove('compressed');await wait(450);$('pressLeft').classList.add('in');$('pressRight').classList.add('in');$('coil').classList.add('compressed');$('gapValue').textContent='72%';log('Вторая подпрессовка: бунт повторно уплотнён.','info');await wait(900)}}

async function feedPass(pass){setPass(pass);let stepIndex=pass===1?2:5;step(stepIndex);mstate(`ПОДАЧА ${pass}/2`,'warn');$('operatorTask').textContent=`ПОДАЧА · ЦИКЛ ${pass}`;$('wireFeed').classList.add('feeding');$('wireLoop').classList.add('on');setMachineSensor('B24',true);setMachineSensor('B28',true);setMachineSensor('B69',true);setEncoderPhase(630,true);log(`Цикл вязки ${pass}: четыре устройства подают проволоку. Счётчики U1–U4 идут в импульсах.`,'info');await tickEnc(.9);$('wireFeed').classList.remove('feeding');step(pass===1?3:6);mstate(`УТЯЖКА ${pass}/2`,'warn');$('operatorTask').textContent=`УТЯЖКА · ЦИКЛ ${pass}`;$('wireLoop').classList.add('tight');setEncoderPhase(settings.tension==='LOW'?220:300,true);headIO.forEach(h=>{h.Y1=true;h.B5=true});renderHmi();log(`Утяжка ${pass}: скорость снижена, проволока выбирает слабину.`,'info');await tickEnc(.7);setEncoderPhase(0,false);setMachineSensor('B28',false);renderHmi()}

async function tiePass(pass){step(pass===1?4:7);mstate(`ВЯЗКА ${pass}/2`,'warn');$('operatorTask').textContent=`4 ГОЛОВЫ · ЦИКЛ ${pass}`;document.querySelectorAll('.head').forEach(h=>h.classList.add('active'));headIO.forEach(h=>{h.Y1=true;h.Y2=true;h.B1=false;h.B3=true;h.B20=false});renderHmi();log(`Цикл ${pass}: одновременно работают 4 вязальные головы — формируются 4 вязки.`,'info');beep(520,80);await wait(550);headIO.forEach(h=>{h.Y2=false;h.Y3=true;h.B8=true});renderHmi();await wait(400);let faultHere=currentFault&&currentFault.pass===pass;for(let i=1;i<=4;i++){let bad=faultHere&&((currentFault.id==='head3'&&i===3)||(currentFault.id==='clamp'&&i===2));let tie=$(`tie${i}${pass===1?'a':'b'}`),head=document.querySelector(`[data-head="${i}"]`);tie.classList.add('on');if(currentFault?.id==='weak'&&faultHere)tie.classList.add('weak');if(bad){tie.classList.add('bad');head.classList.add('fail')}else head.classList.add('ok')}if(faultHere&&currentFault.id==='jam'){$('jamWire').classList.add('on');setMachineSensor('B64',false,true);$('pressRight').classList.add('fault')}if(faultHere&&currentFault.id==='plate2module'){setMachineSensor('B69',false,true);$('pressRight').classList.add('fault')}if(faultHere&&currentFault.id==='b28'){setMachineSensor('B28',false,true);enc[2].moving=false;enc[2].speed=0}headIO.forEach(h=>{h.Y3=false;h.Y5=true;h.B1=true;h.B3=false;h.B20=true});renderHmi();await wait(450);headIO.forEach(h=>{h.Y1=false;h.Y5=false;h.B5=false;h.B8=false});document.querySelectorAll('.head').forEach(h=>h.classList.remove('active'));renderHmi();$('wireLoop').classList.remove('on','tight')}

async function runCycle(){
 if(busy||currentRole!=='operator')return;if(currentFault){log('Новый цикл заблокирован: активная неисправность не устранена.','bad');return}
 busy=true;$('startBtn').disabled=true;alarmAck=false;mechanicCalled=false;resetVisual();currentFault=chooseFault();$('faultCode').textContent='НЕТ АВАРИИ';$('faultCode').className='badge';$('mechanicPrompt').textContent='Ожидание вызова оператора.';badge('ЦИКЛ');$('operatorTask').textContent='ЦИКЛ ЗАПУЩЕН';log('Старт. Реальная схема: сжатие → 4 вязки → ещё 4 вязки → отпуск плит.','info');step(0);await wait(350);await press();await feedPass(1);await tiePass(1);await wait(350);await feedPass(2);await tiePass(2);step(8);mstate('РЕЗКА / ЗАВЕРШЕНИЕ','warn');$('operatorTask').textContent='ЗАВЕРШЕНИЕ';headIO.forEach(h=>h.Y3=true);renderHmi();await wait(450);headIO.forEach(h=>h.Y3=false);renderHmi();step(9);mstate('ВОЗВРАТ ПЛИТ','warn');$('pressLeft').classList.remove('in');$('pressRight').classList.remove('in');$('coil').classList.remove('compressed');$('coil').classList.add('finished');$('gapValue').textContent='78%';setMachineSensor('B58',false);await wait(750);degrade();if(currentFault){state.faults++;state.streak=0;state.score=Math.max(0,state.score-20);$('faultCode').textContent=currentFault.code;$('faultCode').className='badge '+currentFault.severity;$('mechanicPrompt').textContent=`Вызов оператора. Симптом: ${currentFault.sym}`;badge(currentFault.severity==='warn'?'ПРЕДУПР.':'АВАРИЯ',currentFault.severity);mstate(currentFault.severity==='warn'?'ПРЕДУПРЕЖДЕНИЕ':'АВАРИЯ',currentFault.severity);$('operatorTask').textContent='ОСТАНОВ / ВЫЗОВ МЕХАНИКА';log(`${currentFault.code}: ${currentFault.sym}`,currentFault.severity);step(9,'fail');buildInspection()}else{state.coils++;state.streak++;state.score+=150+Math.min(state.streak*5,50);badge(settings.tension==='LOW'?'8 ВЯЗОК · ПЛОТНО':'8 ВЯЗОК · КОНТРОЛЬ','good');mstate('БУНТ ГОТОВ','ok');$('operatorTask').textContent='8 ВЯЗОК ГОТОВО';log('Бунт готов: первый проход 4 вязки + второй проход 4 вязки. После отпускания плит бунт остаётся стянутым.','good');step(9,'done')}renderStats();save();busy=false;$('startBtn').disabled=false;renderHmi()
}

function buildInspection(){let g=$('inspectionGrid');g.innerHTML='';[['b28','B24/B28 и энкодер'],['plate2','Press plate 2 / Node 26'],['guide','Направляющая PP2'],['head','Вязальные головы'],['tension','Трайб / натяжные ролики']].forEach(([id,label])=>{let b=document.createElement('button');b.textContent='Проверить: '+label;b.onclick=()=>inspect(id,b);g.appendChild(b)});$('repairPanel').classList.add('hidden')}
function inspect(id,b){if(!currentFault){log('Активной аварии нет. Можно выполнять профилактику.','info');return}document.querySelectorAll('#inspectionGrid button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');if(id===currentFault.inspect){state.score+=15;log('Проверка дала диагностический признак. Узел найден.','good');showRepairs()}else{state.score=Math.max(0,state.score-5);log('В выбранном узле причина не подтверждена.','warn')}renderStats();save()}
function showRepairs(){let p=$('repairPanel'),a=$('repairActions');p.classList.remove('hidden');a.innerHTML='';[currentFault.repair,'Просто сбросить аварию','Увеличить скорость цикла','Заменить все датчики'].sort(()=>Math.random()-.5).forEach(t=>{let b=document.createElement('button');b.textContent=t;b.onclick=()=>repair(t,b);a.appendChild(b)})}
function repair(t,b){if(!currentFault)return;if(t===currentFault.repair){b.classList.add('good-choice');state.score+=60;if(currentFault.health)state.health[currentFault.health]=Math.min(100,state.health[currentFault.health]+18);log('Неисправность устранена: '+currentFault.node+'.','good');badge('УСТРАНЕНО','good');currentFault=null;$('faultCode').textContent='УСТРАНЕНО';$('mechanicPrompt').textContent='Ремонт выполнен. Машину можно передать оператору.';$('repairPanel').classList.add('hidden');mstate('ГОТОВ','ok');resetVisual()}else{b.classList.add('bad-choice');state.score=Math.max(0,state.score-15);log('Действие не устранило причину.','bad')}renderStats();save()}
function maintain(k){let map={head:['head','Головы очищены и осмотрены.'],guide:['guide','Направляющая PP2 очищена.'],encoder:['encoder','B28 и муфта проверены.'],io:['io','Разъёмы Node 26 / ET200S проверены.'],tension:['tension','Ролики и контур натяжения проверены.']};let [key,msg]=map[k];state.health[key]=Math.min(100,state.health[key]+8);state.score+=5;log(msg,'good');renderStats();save()}

$('chooseOperator').onclick=()=>setRole('operator');$('chooseMechanic').onclick=()=>setRole('mechanic');$('changeRoleBtn').onclick=()=>$('roleGate').classList.remove('hidden');$('operatorTab').onclick=()=>switchTab('operator');$('mechanicTab').onclick=()=>switchTab('mechanic');$('hmiTab').onclick=()=>showHmi('plc');$('openHmiBtn').onclick=()=>showHmi('plc');$('returnBtn').onclick=()=>setRole('operator');$('callMechanicBtn').onclick=()=>{mechanicCalled=true;setRole('mechanic');log(currentFault?'Оператор передал аварийную машину механику.':'Механик вызван для осмотра.','warn')};
$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊':'🔇'};
$('lowBtn').onclick=()=>{if(busy)return;settings.tension='LOW';setPair('lowBtn','highBtn',true);log('Режим натяжения LOW.','info')};$('highBtn').onclick=()=>{if(busy)return;settings.tension='HIGH';setPair('highBtn','lowBtn',true);log('Режим натяжения HIGH.','info')};$('singleBtn').onclick=()=>{if(busy)return;settings.prepress=1;setPair('singleBtn','doubleBtn',true)};$('doubleBtn').onclick=()=>{if(busy)return;settings.prepress=2;setPair('doubleBtn','singleBtn',true)};
$('startBtn').onclick=runCycle;$('ackBtn').onclick=()=>{if(!currentFault){log('Квитировать нечего.','info');return}alarmAck=true;log('Оператор квитировал сообщение. Причина не устранена.','warn')};$('hmiAck').onclick=()=>$('ackBtn').click();$('hmiHome').onclick=()=>setHmiPage('plc');$('hmiBack').onclick=()=>switchTab(currentRole);$('hmiToOperator').onclick=()=>setRole('operator');$('hmiToMechanic').onclick=()=>setRole('mechanic');
document.querySelectorAll('.hmi-page-tabs button').forEach(b=>b.onclick=()=>setHmiPage(b.dataset.page));
$('feederUnitSelect').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedFeedUnit=+b.dataset.unit;$('feederUnitSelect').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderHmi()});
$('headUnitSelect').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedHeadUnit=+b.dataset.unit;$('headUnitSelect').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderHmi()});
$('mechanicPlcBtn').onclick=()=>showHmi('plc');$('mechanicFeederBtn').onclick=()=>showHmi('feeder');$('mechanicHeadBtn').onclick=()=>showHmi('head');document.querySelectorAll('[data-maint]').forEach(b=>b.onclick=()=>maintain(b.dataset.maint));
$('resetBtn').onclick=()=>{if(busy)return;state={score:0,streak:0,coils:0,faults:0,health:{head:100,guide:100,encoder:100,io:100,tension:100}};currentFault=null;save();renderStats();resetVisual();badge('—');mstate('ГОТОВ','ok');$('operatorTask').textContent='ГОТОВ К ЦИКЛУ';$('mechanicPrompt').textContent='Ожидание вызова оператора.';$('faultCode').textContent='НЕТ АВАРИИ';log('Тренажёр сброшен.')};

setInterval(()=>{if(hmiPage)renderHmi()},500);
buildSensors();buildCycle();buildPlcTables();buildInspection();renderStats();resetVisual();