function renderPrepressFlow(cycleIndex){const map=cycleIndex<=0?0:cycleIndex===1?3:cycleIndex===2?7:7;document.querySelectorAll('.flow-step').forEach((e,i)=>e.className='flow-step '+(i<map?'done':i===map?'active':''))}
function syncSensors(){const map={B53:pp.b53,B56:pp.b56,B58:pp.b58,B59:pp.b59,B64:pp.b64,B49:pp.b49};Object.entries(map).forEach(([id,v])=>{const a=document.querySelector(`[data-sensor="${id}"] i`),b=document.querySelector(`[data-status="${id}"]`);if(a)a.className=lampClass(v);if(b)b.className=lampClass(v)});$('pp1Pos').textContent=Math.round(pp.b51pos);$('pp2Pos').textContent=Math.round(pp.b52pos)}
function renderNode26(){document.querySelectorAll('[data-node]').forEach(r=>{const id=r.dataset.node,i=r.querySelector('i');let v=false,bad=currentFault?.id==='node26';if(id==='B56')v=pp.b56;if(id==='B58')v=pp.b58;if(id==='B64')v=pp.b64;if(id==='B52')v=pp.b52pos>0;if(id==='B69')v=pp.b69pos>0;if(id.endsWith('Y21'))v=pp.b49;if(id==='Y68')v=ppOut.Y68;if(id==='Y69')v=ppOut.Y69;i.className=lampClass(v,bad&&['B69','Y68','Y69'].includes(id))})}
function renderHmi(){
 $('hmiClock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('hmiMode').textContent=settings.mode==='REMOTE'?'ДИСТАНЦИОННЫЙ':'МЕСТНЫЙ';$('paramForce').textContent=settings.force+' т';$('paramDouble').textContent=settings.doublePrepress?'ВКЛ':'ОТКЛ';
 syncSensors();renderNode26();
 heads.forEach((n,i)=>{const p=$('encPos'+n),s=$('encSpeed'+n);if(p)p.textContent=Math.round(enc[i].pos);if(s)s.textContent=Math.round(enc[i].speed)});
 document.querySelectorAll('[data-in]').forEach(e=>{const u=+e.dataset.unit-1,id=e.dataset.in;let v=hi[u][id]??false,bad=false;if(id==='B24')v=enc[u].pos>0;if(id==='B2')v=hi[u].B2;e.className='mini-lamp '+(bad?'bad-lamp':v?'on':'')});
 document.querySelectorAll('[data-out]').forEach(e=>{const u=+e.dataset.unit-1,id=e.dataset.out;e.className='mini-lamp '+(hi[u][id]?'on':'')});
 const f=feedUnit-1;$('feederUnitTitle').textContent=feedUnit;$('feedPosition').textContent=Math.round(enc[f].pos);$('feedSpeed').textContent=Math.round(enc[f].speed);$('feedB24').className=lampClass(enc[f].pos>0);$('feedB28').className=lampClass(enc[f].moving,currentFault?.id==='b28'&&f===2);$('feedY22').className=lampClass(hi[f].Y22A);$('feedY23').className=lampClass(hi[f].Y23A||hi[f].Y23B);
 const h=headUnit-1;$('headUnitTitle').textContent=headUnit;const rows=[['B1','Скруч. головка снаружи'],['B2','Повторный вход проволоки'],['B3','Скрутка окончена'],['B5','Скруч. головка внутри'],['B8','Датчик B8 профиля машины'],['B20','Вязальная головка в исходном'],['Y1','Зажим ВКЛ'],['Y2','Зажим ОТКЛ'],['Y3A','Скруч. головка внутрь'],['Y3B','Скруч. головка наружу'],['Y4A','Скрутка'],['Y4B','Сброс/реверс'],['Y5','Обрезка'],['Y6','Обдув/смазка'],['Y20A','Головка к бунту'],['Y20B','Головка от бунта']];$('headLive').innerHTML=rows.map(([id,n])=>`<div><span>${id} ${n}</span><i class="${lampClass(!!hi[h][id],currentFault?.id==='b3'&&id==='B3'&&h===2)}"></i></div>`).join('');
 renderStats();
}
function resetIO(){pp={b53:true,b56:true,b58:false,b59:true,b64:true,b49:false,b52pos:0,b69pos:0,b51pos:0};ppOut={Y80:false,Y81:false,Y82:false,Y83:false,Y68:false,Y69:false,Y30:true};enc=heads.map(()=>({pos:0,speed:0,moving:false}));hi=heads.map(()=>({B1:true,B2:false,B3:false,B5:false,B8:false,B30:false,B20:true,Y1:false,Y2:false,Y3A:false,Y3B:true,Y4A:false,Y4B:false,Y5:false,Y6:false,Y20A:false,Y20B:true,Y22A:false,Y22B:true,Y23A:false,Y23B:false}));renderHmi()}
function resetVisual(){document.querySelectorAll('.tie').forEach(e=>e.classList.remove('on','weak','bad'));document.querySelectorAll('.heads i').forEach(e=>e.className='');$('wireLoop').classList.remove('on','tight');$('jamWire').classList.remove('on');$('pressLeft').className='press-tower left';$('pressRight').className='press-tower right';$('guideCarriage').className='guide-carriage';$('coil').className='coil';$('passValue').textContent='—';$('gapValue').textContent='100%';document.querySelectorAll('.step').forEach(e=>e.className='step');resetIO()}
function setEnc(speed,moving=true){enc.forEach((e,i)=>{e.speed=Math.max(0,speed+Math.round(Math.random()*28-14));e.moving=moving});if(currentFault?.id==='b28'&&currentPass>0){enc[2].moving=false;enc[2].speed=0}renderHmi()}
async function pulseFor(ms){const ticks=Math.max(1,Math.round(ms/100));for(let t=0;t<ticks;t++){enc.forEach(e=>{if(e.moving)e.pos+=Math.max(1,e.speed/18+Math.random()*3)});renderHmi();await wait(100)}}
function chooseFault(){const avg=Object.values(state.health).reduce((a,b)=>a+b,0)/5;let p=.12+(100-avg)/150;if(settings.tension==='HIGH')p+=.10;if(Math.random()>p)return null;const weighted=faults.flatMap(f=>Array(1+Math.floor((100-state.health[f.health])/15)).fill(f));return {...weighted[Math.floor(Math.random()*weighted.length)],pass:Math.random()<.5?1:2,head:1+Math.floor(Math.random()*4)}}
function degrade(){for(const k of Object.keys(state.health))if(Math.random()<.36)state.health[k]=Math.max(45,state.health[k]-1)}
