
$('chooseOperator').onclick=()=>setRole('operator');$('chooseMechanic').onclick=()=>setRole('mechanic');$('changeRoleBtn').onclick=()=>{if(!busy)$('roleGate').classList.remove('hidden')};$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊':'🔇'};
['operator','mechanic','hmi'].forEach(v=>$(v+'Tab').onclick=()=>switchView(v));$('openHmiBtn').onclick=()=>showHmi('main');$('callMechanicBtn').onclick=()=>{called=true;role='mechanic';$('roleBadge').textContent='МЕХАНИК';switchView('mechanic');log('Оператор вызвал механика.','warn')};$('returnBtn').onclick=()=>{role='operator';$('roleBadge').textContent='ОПЕРАТОР';switchView('operator')};
$('forceSlider').oninput=e=>{settings.force=+e.target.value;$('forceLabel').textContent=settings.force+' т';$('forceValue').textContent=settings.force+' t';renderHmi()};$('singleBtn').onclick=()=>{settings.doublePrepress=false;setPair('singleBtn','doubleBtn',true);renderHmi()};$('doubleBtn').onclick=()=>{settings.doublePrepress=true;setPair('doubleBtn','singleBtn',true);renderHmi()};$('lowBtn').onclick=()=>{settings.tension='LOW';setPair('lowBtn','highBtn',true)};$('highBtn').onclick=()=>{settings.tension='HIGH';setPair('highBtn','lowBtn',true)};$('localBtn').onclick=()=>{settings.mode='LOCAL';setPair('localBtn','remoteBtn',true);renderHmi()};$('remoteBtn').onclick=()=>{settings.mode='REMOTE';setPair('remoteBtn','localBtn',true);renderHmi()};
$('startBtn').onclick=runCycle;$('ackBtn').onclick=()=>{alarmAck=true;log('Оператор квитировал сообщение HMI. Причина неисправности остаётся активной до ремонта.','info')};$('resetBtn').onclick=()=>{if(busy)return;currentFault=null;resetVisual();machineState('ГОТОВ','ok');pill('operatorTask','ИСХОДНОЕ');pill('qualityBadge','—');$('hmiAlarm').textContent='—';log('Сброс визуального состояния тренажёра.')};
$('hmiTabs').onclick=e=>{const b=e.target.closest('[data-page]');if(b)setPage(b.dataset.page)};document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>setPage(b.dataset.goto));$('hmiHome').onclick=()=>setPage('main');$('hmiAck').onclick=()=>{$('ackBtn').click()};$('hmiOrigin').onclick=()=>{if(!busy){resetVisual();log('Команда «Исходное»: исполнительные механизмы возвращены в исходное состояние.')}};$('hmiToOperator').onclick=()=>switchView('operator');$('hmiToMechanic').onclick=()=>switchView('mechanic');
$('feederUnitSelect').onclick=e=>{const b=e.target.closest('[data-feedunit]');if(!b)return;feedUnit=+b.dataset.feedunit;document.querySelectorAll('[data-feedunit]').forEach(x=>x.classList.toggle('active',x===b));renderHmi()};$('headUnitSelect').onclick=e=>{const b=e.target.closest('[data-headunit]');if(!b)return;headUnit=+b.dataset.headunit;document.querySelectorAll('[data-headunit]').forEach(x=>x.classList.toggle('active',x===b));renderHmi()};
document.querySelectorAll('[data-openhmi]').forEach(b=>b.onclick=()=>showHmi(b.dataset.openhmi));document.querySelectorAll('[data-maint]').forEach(b=>b.onclick=()=>maintenance(b.dataset.maint));
document.querySelectorAll('[data-enable-head]').forEach(b=>b.onclick=()=>b.classList.toggle('on'));
setInterval(()=>{if(!$('hmiView').classList.contains('hidden'))renderHmi()},700);
buildStatic();renderStats();resetVisual();log('v7 загружена: PDF-алгоритм + профиль твоей машины + двойная обвязка 4+4.','good');
